# FROM dockerhub.priv.iutdelens.ovh/webdevops/php-nginx:8.1-alpine
FROM webdevops/php-nginx:8.1-alpine

RUN apk add postgresql-dev libxml2-dev
# RUN docker-php-ext-install \
#     bcmath \
#     ctype \
#     fileinfo \
#     json \
#     pdo_mysql \
#     pdo_pgsql \
#     tokenizer \
#     xml

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ENV WEB_DOCUMENT_ROOT /app/public
ENV APP_ENV production
WORKDIR /app
COPY . .


RUN composer install --no-interaction --optimize-autoloader --no-dev

RUN cp .env.example .env
RUN touch /app/database/database.sqlite
RUN php artisan key:generate
RUN php artisan jwt:secret
RUN php artisan migrate --force
RUN php artisan db:seed --force
# Optimizing Configuration loading
RUN php artisan config:cache
# Optimizing Route loading
RUN php artisan route:cache

RUN chown -R application:application .